version: '3.8'

services:
  folder_creator:
    image: folder_creator
    build: .
    environment:
      - BASE_PATH=/app/folders
      - ROOT_FOLDER=TestProjectDocker  # Pass the root folder name here
    volumes:
      - /Users/mpadrosg/Documenten/:/app/folders
    command: python /app/create_folders.py
